### PR TITLE
Small quality of life improvements

### PR DESCRIPTION
**Pull request by egze**
- add `.gitignore`
- move `multi_render.ex` to root `lib` folder.

### CODE REVIEW

**Comment by DaTrader** [comment]
Thanks, I'll take .gitignore, but before I merge anything, let's first discuss the following:

1. mix format trims the leading space character in all my first arguments which I then find less readable than my code ("It's not a bug, it's a feature" :). Besides, I don't intend to do that in my local repository, so it will then require either someone else doing an additional mix format after each of my commits or me having to create a new (formatted) branch prior to each commit.

2. I named the folder multi_render intentionally. The library name is phoenix_live_view_ext. Why add another folder level with the same name? I could've simply leave left multi_render.ex in the lib root, but then it would find itself along the .ex files in the forth-coming extensions that are completely unrelated (besides the fact that they add to LiveView functionalies).  I emphasize this because unlike LiveView which is a framework, this one is really just a library and as you yourself said, people will be using just the parts they need. Do you still think it would be better to have a number of unrelated .ex files in the same directory and if so why?

**Comment by egze** [comment]
1. It's your decision in the end. `mix.format` is the norm in the community and it's easier to read code this way for other people. For public projects you can consider how people will read your code and add fixes/features. Because if you are planning to use the power of open-source - it will make life easier for those people (lot's of people even have automatic `mix.format` in their code editors). But having said that - your project, your rules. I respect whatever you chose. Maybe just document in the readme that this is the style that you chose on purpose, so you get no more questions about it.

2. This is the convention. If you look at other libraries - this is the common pattern. Your top level module name is `PhoenixLiveViewExt`, so that is how the folder should be named. If you decide otherwise, it will technically still work, but it will not be the norm.

Some examples:

- https://github.com/avdi/dotenv_elixir/tree/master/lib
- https://github.com/thoughtbot/bamboo/tree/master/lib
- https://github.com/phoenixframework/phoenix_live_view/tree/master/lib

**Comment by DaTrader** [comment]
1. Ok. I'll document it in the README file that I am using a slightly different formatting on purpose. Other than that I am using IdeaJ with a plugin that formats everything else automatically, but fortunately for me, keeps my leading space character intact (unlike the JS plugin which trims them away when code changes the scope :(

2. Ok. But they all have both the .ex file and a folder with the same name in the lib root (not just the folder). So, I guess my folder tree will look as follows when I add the next library component:

```
lib
  distiller
   distilled.ex 
  distiller.ex
  multi_render.ex
```

**Comment by egze** [comment]
The standard way would be:

```
lib
  phoenix_live_view_ext
    distilled.ex 
    multi_render.ex
```

**Comment by DaTrader** [comment]
I don't think so. The pattern is
```
lib
  component_name
  component_name.ex
```

Where the folder contains other component implementation details IF there are any. If there aren't, then there is no folder, just the .ex file. This is not purely an Elixir pattern. It dates back to early '90s as far as I can remember. Here's an examples:
https://github.com/DCzajkowski/snapshy

You could argue that in the above example the author did it wrong, but even the LiveView itself follows this pattern:
```
lib
  phoenix_live_view
  phoenix_live_component.ex
  phoenix_live_view.ex
```  

Had there not been for the actual LiveView complexity and IF it could all have fit into the phoenix_live_view.ex, the framework folder structure would look as follows:

```
lib
  phoenix_live_component.ex
  phoenix_live_view.ex
```

**Comment by egze** [comment]
Ok, I hear you :) Do you want me to leave only the gitignore in the PR?

**Comment by DaTrader** [comment]
If you feel like it, I am ok with you doing all of the following so I can simply merge it:

1, Add the leading space warning to the README file
2. Add .gitignore
3. Move the multi_render.ex to lib and delete the multi_render folder

Then I will republish the hex package so the docs link to the source code properly.

**Comment by egze** [comment]
Cool. Will do it later this evening.

**Comment by DaTrader** [comment]
Great!

**Comment by egze** [comment]
Left the `.gitignore` and removed the top level folder.

Please add the warning to the README file yourself. Since it's your warning, it should come from you ;)

**Pull request merged**
